Repository compose-generator/ccom, pull requests merged in 2021-05, with the labels that each got.

#1 Add semantic analysis
  README.md
  compiler/CMakeLists.txt
  compiler/src/analyzer/analyzer.cpp
  compiler/src/analyzer/analyzer.h
  compiler/src/lexer/lexer.cpp
  compiler/src/lexer/lexer.h
  compiler/src/main.cpp
  compiler/src/main.h
  compiler/src/parser/ast/ContentExprAST.cpp
  compiler/src/parser/ast/ContentExprAST.h
  compiler/src/parser/ast/StmtLstExprAST.h
  compiler/src/parser/parser.cpp
  compiler/src/parser/parser.h
Labels: enhancement, improvement

#2 Interpreter implementation
  cli/main.go
  cli/preprocessor.go
  compiler/CMakeLists.txt
  compiler/src/analyzer/analyzer.cpp
  compiler/src/analyzer/analyzer.h
  compiler/src/interpreter/interpreter.cpp
  compiler/src/interpreter/interpreter.h
  compiler/src/main.cpp
  compiler/src/main.h
  compiler/src/parser/ast/ContentExprAST.cpp
  compiler/src/parser/ast/ContentExprAST.h
  compiler/src/parser/parser.cpp
  compiler/src/parser/parser.h
  media/test-file.yml
Labels: enhancement, improvement

#4 Add support for JSON arrays
  README.md
  compiler/cpp/src/analyzer/analyzer.cpp
  compiler/cpp/src/interpreter/interpreter.cpp
  compiler/cpp/src/lexer/lexer.cpp
  compiler/cpp/src/lexer/lexer.h
  compiler/cpp/src/parser/ast/ComBlockExprAST.h
  compiler/cpp/src/parser/ast/IdentifierExprAST.cpp
  compiler/cpp/src/parser/ast/IdentifierExprAST.h
  compiler/cpp/src/parser/ast/StmtExprAST.h
  compiler/cpp/src/parser/parser.cpp
  media/test-file.yml
Labels: enhancement

#7 Add compiler flag to switch compilers
  cli/main.go
  cli/preprocessor.go
Labels: enhancement, improvement

#6 Support for boolean comparison
  README.md
  compiler/cpp/CMakeLists.txt
  compiler/cpp/src/analyzer/analyzer.cpp
  compiler/cpp/src/analyzer/analyzer.h
  compiler/cpp/src/interpreter/interpreter.cpp
  compiler/cpp/src/interpreter/interpreter.h
  compiler/cpp/src/lexer/Token.h
  compiler/cpp/src/lexer/lexer.h
  compiler/cpp/src/main.h
  compiler/cpp/src/parser/ast/ArbitraryExprAST.h
  compiler/cpp/src/parser/ast/BooleanExprAST.cpp
  compiler/cpp/src/parser/ast/BooleanExprAST.h
  compiler/cpp/src/parser/ast/ComBlockBlockExprAST.h
  compiler/cpp/src/parser/ast/ComBlockExprAST.h
  compiler/cpp/src/parser/ast/ComLineBlockExprAST.h
  compiler/cpp/src/parser/ast/CompStmtExprAST.h
  compiler/cpp/src/parser/ast/ContentExprAST.h
  compiler/cpp/src/parser/ast/ExprAST.h
  compiler/cpp/src/parser/ast/HasStmtExprAST.h
  compiler/cpp/src/parser/ast/IdentifierExprAST.h
  compiler/cpp/src/parser/ast/IfBlockExprAST.h
  compiler/cpp/src/parser/ast/KeyExprAST.h
  compiler/cpp/src/parser/ast/NumberExprAST.h
  compiler/cpp/src/parser/ast/PayloadExprAST.h
  compiler/cpp/src/parser/ast/SectionExprAST.h
  compiler/cpp/src/parser/ast/StmtExprAST.h
  compiler/cpp/src/parser/ast/StmtLstExprAST.h
  compiler/cpp/src/parser/ast/StringExprAST.h
  compiler/cpp/src/parser/ast/ValueExprAST.h
  compiler/cpp/src/parser/parser.cpp
  compiler/cpp/src/parser/parser.h
  media/test-file.yml
Labels: enhancement

#10 Performance optimization & refactoring
  README.md
  compiler/cpp/CMakeLists.txt
  compiler/cpp/src/analyzer/analyzer.cpp
  compiler/cpp/src/analyzer/analyzer.h
  compiler/cpp/src/interpreter/interpreter.cpp
  compiler/cpp/src/interpreter/interpreter.h
  compiler/cpp/src/lexer/Token.h
  compiler/cpp/src/lexer/lexer.cpp
  compiler/cpp/src/lexer/lexer.h
  compiler/cpp/src/parser/ast/ArbitraryExprAST.cpp
  compiler/cpp/src/parser/ast/ArbitraryExprAST.h
  compiler/cpp/src/parser/ast/BooleanExprAST.cpp
  compiler/cpp/src/parser/ast/BooleanExprAST.h
  compiler/cpp/src/parser/ast/ComBlockBlockExprAST.cpp
  compiler/cpp/src/parser/ast/ComBlockBlockExprAST.h
  compiler/cpp/src/parser/ast/ComBlockExprAST.cpp
  compiler/cpp/src/parser/ast/ComBlockExprAST.h
  compiler/cpp/src/parser/ast/ComLineBlockExprAST.cpp
  compiler/cpp/src/parser/ast/ComLineBlockExprAST.h
  compiler/cpp/src/parser/ast/CompStmtExprAST.cpp
  compiler/cpp/src/parser/ast/CompStmtExprAST.h
  compiler/cpp/src/parser/ast/ContentBlockExprAST.cpp
  compiler/cpp/src/parser/ast/ContentBlockExprAST.h
  compiler/cpp/src/parser/ast/ContentExprAST.cpp
  compiler/cpp/src/parser/ast/ContentExprAST.h
  compiler/cpp/src/parser/ast/ExprAST.cpp
  compiler/cpp/src/parser/ast/ExprAST.h
  compiler/cpp/src/parser/ast/HasStmtExprAST.cpp
  compiler/cpp/src/parser/ast/HasStmtExprAST.h
  compiler/cpp/src/parser/ast/IdentifierExprAST.cpp
  compiler/cpp/src/parser/ast/IdentifierExprAST.h
  compiler/cpp/src/parser/ast/IfBlockExprAST.cpp
  compiler/cpp/src/parser/ast/IfBlockExprAST.h
  compiler/cpp/src/parser/ast/KeyExprAST.cpp
  compiler/cpp/src/parser/ast/KeyExprAST.h
  compiler/cpp/src/parser/ast/NumberExprAST.cpp
  compiler/cpp/src/parser/ast/NumberExprAST.h
  compiler/cpp/src/parser/ast/PayloadExprAST.cpp
  compiler/cpp/src/parser/ast/PayloadExprAST.h
  compiler/cpp/src/parser/ast/SectionExprAST.cpp
  compiler/cpp/src/parser/ast/SectionExprAST.h
  compiler/cpp/src/parser/ast/StmtExprAST.cpp
  compiler/cpp/src/parser/ast/StmtExprAST.h
  compiler/cpp/src/parser/ast/StmtLstExprAST.cpp
  compiler/cpp/src/parser/ast/StmtLstExprAST.h
  compiler/cpp/src/parser/ast/StringExprAST.cpp
  compiler/cpp/src/parser/ast/StringExprAST.h
  compiler/cpp/src/parser/ast/TopLevelExprAST.cpp
  compiler/cpp/src/parser/ast/TopLevelExprAST.h
  compiler/cpp/src/parser/ast/ValueExprAST.cpp
  compiler/cpp/src/parser/ast/ValueExprAST.h
  compiler/cpp/src/parser/parser.cpp
  compiler/cpp/src/parser/parser.h
  media/class-diagram.drawio
  media/class-diagram.svg
Labels: bug, improvement

#11 Consider operator in CompStmt
  compiler/cpp/src/interpreter/interpreter.cpp
  compiler/cpp/src/interpreter/interpreter.h
  media/test-file.yml
Labels: enhancement

#12 More comparison operators
  compiler/cpp/src/analyzer/analyzer.cpp
  compiler/cpp/src/interpreter/interpreter.cpp
  compiler/cpp/src/lexer/Token.h
  compiler/cpp/src/lexer/lexer.cpp
  compiler/cpp/src/lexer/lexer.h
  compiler/cpp/src/parser/ast/CompStmtExprAST.h
  compiler/cpp/src/parser/parser.cpp
  media/test-data.json
  media/test-file.html
Labels: bug, enhancement

#13 Implement Java FileReader & Tests
  .github/workflows/ci-java.yml
  compiler/java/.gitignore
  compiler/java/.idea/misc.xml
  compiler/java/.idea/vcs.xml
  compiler/java/pom.xml
  compiler/java/src/main/java/com/c/filereader/FileReader.java
  compiler/java/src/main/java/com/c/filereader/LimitedQueue.java
  compiler/java/src/main/java/com/c/filereader/MaxLookAheadException.java
  compiler/java/src/main/java/com/c/filereader/UnexpectedCharException.java
  compiler/java/src/main/java/com/c/lexer/Lexer.java
  compiler/java/src/main/java/com/c/lexer/Token.java
  compiler/java/src/main/java/com/c/lexer/TokenType.java
  compiler/java/src/test/java/com/c/InitialTest.java
  compiler/java/src/test/java/com/c/filereader/FileReaderTest.java
  compiler/java/src/test/java/com/c/testfiles/FileToString.java
  compiler/java/src/test/java/com/c/testfiles/TwoBasicLines.txt
Labels: enhancement

#5 Release workflow with cross-compilation build
  .github/workflows/publish.yml
  .goreleaser.yml
  cli/ccom.go
  cli/go.mod
  cli/go.sum
  compile-test-file.bat
  compiler/cpp/CMakeLists.txt
  wix.json
Labels: enhancement, improvement

#27 Add Dependabot config
  .github/dependabot.yml
Labels: improvement

#26 CLI benchmark mode
  README.md
  cli/ccom.go
  cli/preprocessor.go
  compiler/cpp/.gitignore
  compiler/cpp/src/main.cpp
  compiler/cpp/src/main.h
Labels: enhancement

#28 Reader unit tests
  .github/workflows/ci-cpp.yml
  .github/workflows/ci-go.yml
  .github/workflows/publish.yml
  compiler/cpp/.gitignore
  compiler/cpp/.run/All CTest.run.xml
  compiler/cpp/.run/CCom_run.run.xml
  compiler/cpp/.run/CCom_test.run.xml
  compiler/cpp/CMakeLists.txt
  compiler/cpp/setup-libs.bat
  compiler/cpp/src/CMakeLists.txt
  compiler/cpp/src/analyzer/Analyzer.h
  compiler/cpp/src/exception/MaxLookaheadException.cpp
  compiler/cpp/src/exception/MaxLookaheadException.h
  compiler/cpp/src/exception/UnexpectedCharException.h
  compiler/cpp/src/interpreter/Interpreter.cpp
  compiler/cpp/src/main.cpp
  compiler/cpp/src/reader/Reader.cpp
  compiler/cpp/src/reader/Reader.h
  compiler/cpp/src/util/JSONParser.h
  compiler/cpp/test/CMakeLists.txt
  compiler/cpp/test/ReaderTest.cpp
  compiler/cpp/test/main.cpp
Labels: test

#29 CLI enhancements
  README.md
  cli/ccom.go
  cli/go.mod
  cli/go.sum
  cli/preprocessor.go
  cli/util/cli.go
Labels: enhancement, size/L

#25 Re-implement compiler with classes
  .github/workflows/ci-cpp.yml
  .github/workflows/ci-go.yml
  compiler/cpp/.run/All CTest.run.xml
  compiler/cpp/.run/CCom_run.run.xml
  compiler/cpp/.run/CCom_test.run.xml
  compiler/cpp/CMakeLists.txt
  compiler/cpp/setup-libs.bat
  compiler/cpp/src/CMakeLists.txt
  compiler/cpp/src/analyzer/Analyzer.cpp
  compiler/cpp/src/analyzer/Analyzer.h
  compiler/cpp/src/analyzer/analyzer.h
  compiler/cpp/src/exception/MaxLookaheadException.cpp
  compiler/cpp/src/exception/MaxLookaheadException.h
  compiler/cpp/src/exception/UnexpectedCharException.cpp
  compiler/cpp/src/exception/UnexpectedCharException.h
  compiler/cpp/src/interpreter/Interpreter.cpp
  compiler/cpp/src/interpreter/Interpreter.h
  compiler/cpp/src/interpreter/interpreter.h
  compiler/cpp/src/lexer/Lexer.cpp
  compiler/cpp/src/lexer/Lexer.h
  compiler/cpp/src/lexer/Token.h
  compiler/cpp/src/lexer/lexer.cpp
  compiler/cpp/src/lexer/lexer.h
  compiler/cpp/src/main.cpp
  compiler/cpp/src/main.h
  compiler/cpp/src/parser/Parser.cpp
  compiler/cpp/src/parser/Parser.h
  compiler/cpp/src/parser/parser.cpp
  compiler/cpp/src/parser/parser.h
  compiler/cpp/src/reader/Reader.cpp
  compiler/cpp/src/reader/Reader.h
  compiler/cpp/src/util/JSONParser.cpp
  compiler/cpp/src/util/JSONParser.h
  compiler/cpp/test/CMakeLists.txt
  compiler/cpp/test/ReaderTest.cpp
  compiler/cpp/test/main.cpp
Labels: bug, improvement

#30 Add installation instructions
  README.md
Labels: enhancement, improvement, size/M
